# Generated by Django 5.2.1 on 2025-05-30 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentverification',
            options={'ordering': ['-updated_at'], 'verbose_name': "Vérification d'identité", 'verbose_name_plural': "Vérifications d'identité"},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_creation'], 'permissions': [('valider_transaction', 'Peut valider les transactions'), ('annuler_transaction', 'Peut annuler les transactions')], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('portefeuille', 'Portefeuille'), ('carte', 'Carte bancaire'), ('orange', 'Orange Money'), ('wave', 'Wave'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to='verifications/permis/', verbose_name='Permis de conduire'),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='verifications/ids/', verbose_name="Carte d'identité"),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='notes',
            field=models.TextField(blank=True, help_text="Notes internes pour l'équipe de vérification", null=True),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='verifications/passeports/', verbose_name='Passeport'),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='registration_card',
            field=models.FileField(blank=True, null=True, upload_to='verifications/cartegrise/', verbose_name='Carte grise'),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/selfies/', verbose_name='Selfie de vérification'),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('documents_required', 'Documents manquants')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='vehicle_insurance',
            field=models.FileField(blank=True, null=True, upload_to='verifications/assurances/', verbose_name="Attestation d'assurance"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='portefeuille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='location.portefeuille'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('annule', 'Annulé'), ('completed', 'Complété'), ('refunded', 'Remboursé'), ('failed', 'Échoué')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('virement', 'Virement'), ('paiement', 'Paiement reçu'), ('paiement_service', 'Paiement pour service'), ('remboursement', 'Remboursement')], max_length=20),
        ),
    ]
