version: '3.8'

services:
  web:
    build: .
    command: gunicorn moncaisson.wsgi:application --bind 0.0.0.0:8000
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./logs:/app/logs
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    environment:
      - DEBUG=0
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data: